### ISSUE TITLE
Separate filter and algorithm logic

### ISSUE THREAD

**Issue by kodabb** [facebook/transform360#1]
Hi, Libav/FFmpeg developer here: let me first say it's great that Facebook is willing to open their tools and share IP. However the current state of this project makes it really hard for people to use (not many can actually edit source code), and the incompatible license terms prevents this filter to actually get merged in upstream.

I'm not going to judge the license selection, and I can understand your necessity of keeping rights within the company, however this should not leak to the filter itself, and there are ways to prevent this. The common approach for example is to release a library with a relatively simple API, with any license makes sense to you, and then release a lgpl filter which gets enabled with --enable-nonfree configure option. This would allow the basic filtering to be always available, and all the improvements to the library would still be yours.

Of course there are other options, and I know that this filter is targeting a niche audience (for now), but the right way to spread this technology is to let it reach as many users as possible, and without community/upstreaming support this severely impacts any chance of succeeding.

**Comment by puffpio** [comment]
Hi kodabb thanks for the tip!

We have been thinking of this too and I want to move in this direction. It's been in my todo list and you will definitely see this in the future.

Keeping this issue open to keep me honest :)

**Comment by deepvoice** [comment]
+1

**Comment by D3m0n92** [comment]
+1

**Comment by adamchen0510** [comment]
+1

**Comment by thonatos** [comment]
+1

**Comment by fritzprix** [comment]
+1

**Comment by abuisine** [comment]
+1

**Comment by boblaublaw** [comment]
+1

**Comment by rzurad** [comment]
+1

**Comment by qmphobby** [comment]
+1

**Comment by yyakult** [comment]
+1

**Comment by puffpio** [comment]
Hey guys. Hope you all have seen, we have recently updated the repo and have separated the algorithm with the filter. Hopefully that helps.
