### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by sjames1958gm** [facebook/transform360#24]
The build instructions are somewhat lacking. Any pointers on how to build for linux?

**Comment by telganainy** [comment]
Hi,

Checkout this thread, it maybe help you build the code: [https://github.com/facebook/transform360/issues/22](url)

For Linux, you may need to make another minor thing:

- In "vf_transform360.c", #include "transform360/V..." make the first letter capital in transform. e.g. #include "Transform360/V..." for both includes.

It should work for you, I tried it for both Mac and Ubuntu,
Hope that helps.

**Comment by rpenggithub** [comment]
Thanks, telganainy. A more detailed readme file is coming.

**Comment by puffpio** [comment]
closing out as cmake instructions were added
