### ISSUE TITLE
Pyramid encoding

### ISSUE THREAD

**Issue by amelierosser** [facebook/transform360#29]
Hello,

After building the project locally and converting an equirectangular video I noticed it only outputs a cube map video. Do you plan on realising the pyramid transform which is mentioned in this post? https://code.facebook.com/posts/1126354007399553/next-generation-video-encoding-techniques-for-360-video-and-vr/

**Comment by HazemSamir** [comment]
Hello Amelie,

Did you check this issues #7 and #23 ?

**Comment by amelierosser** [comment]
Ah I didn't notice those issues. I'll close.
