### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by laohumultimedia** [facebook/transform360#31]
as you can see, the performance continue to drop
frame=   42 fps= 12 q=0.0 size=       0kB time=00:00:02.22 bitrate=   0.0kbits/s speed=0.629x    
frame=  335 fps= 16 q=28.0 size=    8388kB time=00:00:13.95 bitrate=4924.1kbits/s speed=0.646x    
frame=  779 fps= 16 q=28.0 size=   24771kB time=00:00:31.71 bitrate=6398.0kbits/s speed=0.634x    
frame= 1004 fps= 15 q=28.0 size=   38468kB time=00:00:40.70 bitrate=7742.4kbits/s speed=0.61x     
frame= 1128 fps= 15 q=28.0 size=   49041kB time=00:00:45.67 bitrate=8796.5kbits/s speed=0.597x    
frame= 1420 fps= 14 q=28.0 size=   72797kB time=00:00:57.34 bitrate=10398.5kbits/s speed=0.578x    
frame= 1901 fps= 14 q=28.0 size=  106590kB time=00:01:16.59 bitrate=11399.6kbits/s speed=0.566x    
frame= 2514 fps= 14 q=28.0 size=  140127kB time=00:01:41.11 bitrate=11352.4kbits/s speed=0.561x    
frame= 3328 fps= 14 q=28.0 size=  187116kB time=00:02:13.66 bitrate=11467.6kbits/s speed=0.557x    
frame= 4115 fps= 14 q=28.0 size=  233225kB time=00:02:45.15 bitrate=11568.6kbits/s speed=0.555x 
i check the cv::remap function(didn't use gnu acceleration), and found it runs slower and slower.  I tested about 4500 frames and i wonder if the performance will continue to drop ?  is this the cv::remap issue? do we have any solution?

**Comment by laohumultimedia** [comment]
the performance issue only exists in the newest version, i'm quite sure it's caused by cv::remap function.

**Comment by evgenykuzyakov** [comment]
Can you share more details on how to reproduce the issue? E.g. ffmpeg command that you're running.

**Comment by laohumultimedia** [comment]
ffmpeg -i source.mp4 -vf transform360="input_stereo_format=MONO :output_layout=CUBEMAP_32 :max_cube_edge_length=1024"  cube_32_normal.mp4
you can check the speed item.  What's more, i profile the cv::remap function(count average cost), and found it taken more and more time(average time continue  to increase).

**Comment by laohumultimedia** [comment]
I tested on OS X and Centos， both can reproduce the issue.

**Comment by laohumultimedia** [comment]
I use opencv 3.2, with ipp, no Cuda, no Tpp, no Openvx.
