### ISSUE TITLE
Is there a way to test offset cubemaps?

### ISSUE THREAD

**Issue by masmil1988** [facebook/transform360#33]
As I understand, this code should also be related to [this article](https://code.facebook.com/posts/637561796428084/end-to-end-optimizations-for-dynamic-streaming/), i.e. it should be possible to create offset cubemaps (as well as cubemaps) starting from an equirectangular video.

I'm able to use it and setting an offset (by using the params `cube_offcenter_x`, `cube_offcenter_y` and `cube_offcenter_z`) and the output video is actually compliant with my expectations.

The problem is: when I try to render the video on the internal faces of a cube, by translating camera in accordance with the `cube_offcenter_*` params previously used, the video is not rendered properly (I'm using OpenGL ES on Android) but instead it has some distortions. May you provide some additional details on how to map the video (the offset cubemap one) inside of the cube? Are there some examples of how it actually works or some tool to see it working?

Thanks
<table>
<tr><td><img src="https://cloud.githubusercontent.com/assets/6042561/24107256/88dfba98-0d8a-11e7-8e18-f93c0f1531f7.jpg" alt="Offset to 0" width="300"/></td>
<td><img src="https://cloud.githubusercontent.com/assets/6042561/24107263/8eb38062-0d8a-11e7-88db-7a69c6b92064.jpg" alt="Z Offset to 0.50" width="300"/></td>
<tr><td>Offset to 0</td><td>Z Offset to 0.50</td></tr>
</table>

**Comment by yyakult** [comment]
+1

**Comment by yyakult** [comment]
BTW, I have read the article about offset cubemaps. I am considering about how the offset cubemaps are genreated. 
In my opinion, the minimum resolution that offset cubemaps can reach without distorting the viewport quality is 8.3% (1/12) to the original cubemap. In this situation, the offset cubemap records only the content inside the viewport.

**Comment by yyakult** [comment]
I am wondering what is the use case of offset cubemaps?

**Comment by masmil1988** [comment]
The use case is _decreasing the overall resolution of the video without decreasing the quality of the viewport_.

**Comment by yyakult** [comment]
Thank you very much. 
BTW, I am wondering what is the real meaning of ***without decreasing the quality of the viewport***.
For a cubemap projection (CMP), with a 90-degree x 90-degree viewport, the HMD can render a face of a cube. Let's assume the front face is rendered.
As can be seen in [this video](https://www.youtube.com/watch?v=uSHTsGNFmeM&index=7&list=PLL2xVXGs1SP7RjXUBwur43flR7tRcbYLD) presented by Cass, the offset cubemaps try to reserve the details in the front face. The new front face of a offset cubemap is a part of the front face in original 100% resolution CMP. Thus the overall resolution is decreased. 
It is true that the quality of the new front face doesn't decrease.  However, the content in the front face of the original 100% resolution CMP is mapped to ***multiple faces*** of the offset cubemap. I think the quality of the viewport in the 100% resolution CMP is decreased.

**Comment by puffpio** [comment]
this primarily lets us having higher quality when downscaling. it's not
useful if you want to achieve a 100% resolution CMP

assume an original 1536x1536 cube face size and we are downscaling to a
512x512 cube face size
since the original front face is now warped to map to multiple faces, that
means the "front face" now has more pixels allocated to it relative to the
other original faces. in the end we have a 512x512 cube face size output,
but the "front face" viewport now uses more pixel area and thus has higher
resolution

**Comment by yyakult** [comment]
@puffpio Got it! Thanks a lot!
