### ISSUE TITLE
Still lacking build documentation. 

### ISSUE THREAD

**Issue by danrossi** [facebook/transform360#36]
How to include opencv into the build ? I tried everything and still get this

```
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

```

tried

```
export OpenCV_INCLUDE_DIRS=opencv/include
```

and

```
export OpenCV_DIR=opencv/
```

**Comment by danrossi** [comment]
This OpenCV dependancy has been very vague. It seems many people are having issues. 

I installed via apt and was able to properly run cmake. Trying to link to the opencv sources won't work. Trying to build opencv from sources is a dead end and throws errors. The build documentation for opencv is very vague. 

```
sudo apt-get install libopencv-dev
```

```
cmake ./
-- Configuring done
-- Generating done
-- Build files have been written to: transform360/Transform360
```

```
make
Scanning dependencies of target Transform360
[ 33%] Building CXX object CMakeFiles/Transform360.dir/Library/VideoFrameTransform.cpp.o
[ 66%] Building CXX object CMakeFiles/Transform360.dir/Library/VideoFrameTransformHandler.cpp.o
[100%] Linking CXX static library libTransform360.a

```

**Comment by danrossi** [comment]
Full install for Ubuntu

```
sudo apt-get install ffmpeg
sudo apt-get install libopencv-dev libxvidcore-dev
sudo apt-get install nasm libass-dev libfdk-aac-dev libvpx-dev 
cmake ./
make
sudo make install
```

Edit vf_transform360.c that is copied into FFmpeg/libavfilter

Change the include path to

```
#include "Transform360/Library/VideoFrameTransformHandler.h"
#include "Transform360/Library/VideoFrameTransformHelper.h"
```


```
cd ../FFmpeg
 ./configure --prefix=/usr/local/transform/ffmpeg --enable-gpl
 --enable-nonfree --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libvpx --enable-libx264 --enable-lib
xvid --enable-libopencv --extra-libs='-lTransform360 -lstdc++'
make
sudo make install
```
```
 /usr/local/transform/ffmpeg/bin/ffmpeg
ffmpeg version N-86781-gd8f1982 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr/local/transform/ffmpeg --enable-gpl --enable-nonfree --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libvpx --enable-libx264 --enable-libxvid --enable-libopencv --extra-libs='-lTransform360 -lstdc++'
  libavutil      55. 67.100 / 55. 67.100
  libavcodec     57.100.104 / 57.100.104
  libavformat    57. 75.100 / 57. 75.100
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 95.100 /  6. 95.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

**Comment by qbunt** [comment]
@danrossi thanks a bunch for that, super helpful

**Comment by evgenykuzyakov** [comment]
I've updated the build documentation for Ubuntu. Hope it's going to help.

**Comment by danrossi** [comment]
I haven't got that far to work out how to implement it. My encode hangs for some reason and must need some serious power. 

I haven't seen any example cubemap shader rendering for three.js etc. 

Coming back to it. At least it compiled.

**Comment by evgenykuzyakov** [comment]
We do have sample 360 player that plays equirect: https://github.com/fbsamples/360-video-player-for-android
To play cubemap video you just need to modify the geometry in Sphere.java to be 6 faces of the cube with 2 triangles each. Properly provide UV coordinates and it should work.

You can take a look at https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Animating_textures_in_WebGL for how to render video in webgl. It doesn't require three.js for something simple as a 360 video.

**Comment by danrossi** [comment]
I meant a shader example for webgl. This can be implemented back into three.js. It doesn't necessarily need to be for that. 

You mention uv coordinates so if it requires repacking uv's I see no example for that either.  

It's ok I'll come back to it once I can make an encode transform first.
