### ISSUE TITLE
From cubmap to equirectangular

### ISSUE THREAD

**Issue by jo-chemla** [facebook/transform360#37]
A nice option would be to allow for the inverse transformation with ffmpeg, from cubmap to equirectangular. One would give ffmpeg a sequence of 6xN files, one for each face of the cube for the N frames, and convert to N equirectangular frames.

**Comment by kcircnc** [comment]
Equirect -> cubemap is a lossy transformation, as the resolution of the former is higher than the latter. This implies that a cubmap -> equirect transform would not be possible without interpolation which will degrade the image quality.

**Comment by jo-chemla** [comment]
That's right, but one might adjust the resolution of the cubemap to ensure the equirect at desired resolution will not be affected too much by interpolation. Let say I want a 4k equirect (about 2160p), I would produce a cubemap with each face side having 2048px - or the correct amount so that the interpolation does not affect too much the result.

**Comment by evgenykuzyakov** [comment]
I've added an option to specify different input_layout. You can now pass cubemap_32 in the input_layout and equirect as an output_layout. It'll generate an equirect from the cubemap_32 layout.
It doesn't let you use multiple videos. But if you combine them into single cubemap_32 layout then you can get the equirect output. Depending on what expansion around the faces you use, you may want to specify the input_expand_coef. If you don't use any expansion around the edges of each face, then specify input_expand_coef=1.0

Example command to run reverse cubemap_32 to equirectangular format is:

    ffmpeg -i input.mp4 -vf transform360=input_layout=cubemap_32:input_expand_coef=1.0:output_layout=equirect:w=2048:h=1024 -c:v libx264 -preset veryfast -crf 10 -threads 0 -c:a copy output.mp4

**Comment by jo-chemla** [comment]
thanks a lot! would be very helpful to be able to provide six input sequences - 6 images for each frame of the 360 sequence, the naming to be defined by ffmpeg if images are given in determined order (first input is front, second is left, ...), but I imagine it will require more work. Nice addition!

**Comment by evgenykuzyakov** [comment]
You probably can use complex filter to merge 6 images into 1 and then chain transform filter with it. Example of complex filters: https://github.com/nwochaadim/ffmpeg-installation/wiki/Applying-complex-filters-to-videos

**Comment by JaiiRLopeZ** [comment]
@evgenykuzyakov @jo-chemla @kcircnc Do you know to change the order of the faces cubemap?

**Comment by rodrigopolo** [comment]
How about YouTube's cube map to equirectangular?
