### ISSUE TITLE
Transform360 Building Issue

### ISSUE THREAD

**Issue by hangil2478** [facebook/transform360#40]
Hi.

I think I have checked quite many issues related to my problem but I am not able to fix it.
The problem is 
./configure --enable-libopencv
generates an error message, "ERROR: opencv not found".

#36 suggested to install ffmpeg by "apt-get install ffmpeg". However, the source files generated from this command does not have configure file in it.

I cloned the latest version of opencv and ffmpeg from github and installed them by using official guideline.

#22 suggested to compile transform360 by changing CMakeLists.txt. I did the same thing as telganainy suggested and compiled it without any errors.

I think the main problem is because of the link between opencv and ffmpeg but owing to some version issues or whatever, it doesn't work..

Any suggestions? Thanks in advance.

**Comment by EthanXzhang** [comment]
I met this error "opencv not found" a week ago.
It cause by the missing file or path in pkg-config.
Refer to the solution : https://prateekvjoshi.com/2013/10/18/package-opencv-not-found-lets-find-it/
FFmpeg config command "--enable-libopencv" using pkg-config the link the library. You can also using the command "--extra-ldflags" and "--extra-libs" to add the library.
By the way, when I solved this error, another error "undefined reference *** opencv" appeared. I am now trying to solve it.
Wish you good luck.

**Comment by hangil2478** [comment]
@EthanXzhang 
Hi. I have already tried your solution but it didn't work.
I set the environment by "$ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig" and the pkgconfig folder contains the "opencv.pc" file as well.

The versions of opencv and ffmpeg are 3.3.0 and 3.3.git the most recent versions of each.
I'm using ubuntu14.04.

**Comment by EthanXzhang** [comment]
@hangil2478 
Firstly, try the cmd "pkg-config --list-all", see whether the OPENCV on the list or not.And, try "OPENCV_VERSION" see if the opencv is correctly install.
If all of above is right,Check the opencv.pc file. It has a path point to the include and lib.Check it.
Secondly, if can not solve the pkg-config, suggest you can try to add opencv as a extra-libs and extra-include.You can cancel the "enable-libopencv" and using command "--extra-ldflags" and "--extra-libs" path pointed to the opencv libs and include.
Wish you good luck.

**Comment by hangil2478** [comment]
@EthanXzhang 

Hi.  I tried your solution but it generates an error saying "C compiler test failed".

So, instead, I solved this issue by using "--extra-ldflags" and "--extra-cflags" options. I have written them below.

./configure --prefix=/usr/local/transform/ffmpeg --enable-gpl --enable-nonfree --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libvpx --enable-libx264 --enable-libxvid --extra-libs='-lTransform360 -lstdc++' --extra-ldflags="-L/usr/local/lib" --extra-cflags="-l/opt/opencv/include/opencv"

However, it still generates other errors. The details of the error message is written below.

LD	ffmpeg_g
/usr/local/lib/libTransform360.a(VideoFrameTransformHandler.cpp.o): In function `cvflann::anyimpl::big_any_policy<cv::String>::static_delete(void**)':
VideoFrameTransformHandler.cpp:(.text._ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE13static_deleteEPPv[_ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE13static_deleteEPPv]+0x15): undefined reference to `cv::String::deallocate()'
/usr/local/lib/libTransform360.a(VideoFrameTransformHandler.cpp.o): In function `cvflann::anyimpl::big_any_policy<cv::String>::move(void* const*, void**)':
VideoFrameTransformHandler.cpp:(.text._ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE4moveEPKPvPS5_[_ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE4moveEPKPvPS5_]+0x10): undefined reference to `cv::String::deallocate()'
VideoFrameTransformHandler.cpp:(.text._ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE4moveEPKPvPS5_[_ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE4moveEPKPvPS5_]+0x24): undefined reference to `cv::String::deallocate()'
/usr/local/lib/libTransform360.a(VideoFrameTransformHandler.cpp.o): In function `cv::Mat::~Mat()':
VideoFrameTransformHandler.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x81): undefined reference to `cv::Mat::deallocate()'
VideoFrameTransformHandler.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x71): undefined reference to `cv::fastFree(void*)'
/usr/local/lib/libTransform360.a(VideoFrameTransformHandler.cpp.o): In function `std::_Rb_tree<int, std::pair<int const, std::vector<cv::Mat, std::allocator<cv::Mat> > >, std::_Select1st<std::pair<int const, std::vector<cv::Mat, std::allocator<cv::Mat> > > >, std::less<int>, std::allocator<std::pair<int const, std::vector<cv::Mat, std::allocator<cv::Mat> > > > >::_M_erase(std::_Rb_tree_node<std::pair<int const, std::vector<cv::Mat, std::allocator<cv::Mat> > > >*)':
VideoFrameTransformHandler.cpp:(.text._ZNSt8_Rb_treeIiSt4pairIKiSt6vectorIN2cv3MatESaIS4_EEESt10_Select1stIS7_ESt4lessIiESaIS7_EE8_M_eraseEPSt13_Rb_tree_nodeIS7_E[_ZNSt8_Rb_treeIiSt4pairIKiSt6vectorIN2cv3MatESaIS4_EEESt10_Select1stIS7_ESt4lessIiESaIS7_EE8_M_eraseEPSt13_Rb_tree_nodeIS7_E]+0xb1): undefined reference to `cv::fastFree(void*)'
VideoFrameTransformHandler.cpp:(.text._ZNSt8_Rb_treeIiSt4pairIKiSt6vectorIN2cv3MatESaIS4_EEESt10_Select1stIS7_ESt4lessIiESaIS7_EE8_M_eraseEPSt13_Rb_tree_nodeIS7_E[_ZNSt8_Rb_treeIiSt4pairIKiSt6vectorIN2cv3MatESaIS4_EEESt10_Select1stIS7_ESt4lessIiESaIS7_EE8_M_eraseEPSt13_Rb_tree_nodeIS7_E]+0xec): undefined reference to `cv::Mat::deallocate()'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `VideoFrameTransform::filterSegment(cv::Mat const&, cv::Mat&, cv::Mat const&, cv::Mat const&, int, int, int, int, int)':
VideoFrameTransform.cpp:(.text+0x4b1): undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Rect_<int> const&)'
VideoFrameTransform.cpp:(.text+0x4c9): undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Rect_<int> const&)'
VideoFrameTransform.cpp:(.text+0x590): undefined reference to `cv::sepFilter2D(cv::_InputArray const&, cv::_OutputArray const&, int, cv::_InputArray const&, cv::_InputArray const&, cv::Point_<int>, double, int)'
VideoFrameTransform.cpp:(.text+0x628): undefined reference to `cv::fastFree(void*)'
VideoFrameTransform.cpp:(.text+0x6c0): undefined reference to `cv::fastFree(void*)'
VideoFrameTransform.cpp:(.text+0x6dc): undefined reference to `cv::Mat::deallocate()'
VideoFrameTransform.cpp:(.text+0x6ec): undefined reference to `cv::Mat::deallocate()'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `calculateKernel(float)':
VideoFrameTransform.cpp:(.text+0x7a7): undefined reference to `cv::Mat::zeros(int, int, int)'
VideoFrameTransform.cpp:(.text+0x952): undefined reference to `cv::Mat::convertTo(cv::_OutputArray const&, int, double, double) const'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `VideoFrameTransform::generateKernelAndFilteringConfig(int, int, float, float, cv::Mat const&, int, int, int)':
VideoFrameTransform.cpp:(.text+0x28c0): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
VideoFrameTransform.cpp:(.text+0x28e0): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
VideoFrameTransform.cpp:(.text+0x296d): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `VideoFrameTransform::calcualteFilteringConfig(int, int, int, int, int)':
VideoFrameTransform.cpp:(.text+0x2f13): undefined reference to `cv::fastFree(void*)'
VideoFrameTransform.cpp:(.text+0x304e): undefined reference to `cv::Mat::deallocate()'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `VideoFrameTransform::filterPlane(cv::Mat const&, int, int)':
VideoFrameTransform.cpp:(.text+0x3b77): undefined reference to `cv::Mat::zeros(cv::Size_<int>, int)'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `VideoFrameTransform::generateMapForPlane(int, int, int, int, int)':
VideoFrameTransform.cpp:(.text+0x3f6d): undefined reference to `cv::Mat::create(int, int const*, int)'
VideoFrameTransform.cpp:(.text+0x41e4): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
VideoFrameTransform.cpp:(.text+0x420c): undefined reference to `cv::Mat::deallocate()'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `VideoFrameTransform::transformPlane(cv::Mat const&, cv::Mat&, int, int, int, int)':
VideoFrameTransform.cpp:(.text+0x45a7): undefined reference to `cv::fastFree(void*)'
VideoFrameTransform.cpp:(.text+0x47d8): undefined reference to `cv::Mat::create(int, int const*, int)'
VideoFrameTransform.cpp:(.text+0x47ed): undefined reference to `cv::Mat::operator=(cv::Scalar_<double> const&)'
VideoFrameTransform.cpp:(.text+0x49ee): undefined reference to `cv::remap(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&, int, int, cv::Scalar_<double> const&)'
VideoFrameTransform.cpp:(.text+0x4a85): undefined reference to `cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)'
VideoFrameTransform.cpp:(.text+0x4ae7): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
VideoFrameTransform.cpp:(.text+0x4d90): undefined reference to `cv::remap(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&, int, int, cv::Scalar_<double> const&)'
VideoFrameTransform.cpp:(.text+0x4ddd): undefined reference to `cv::Mat::deallocate()'
VideoFrameTransform.cpp:(.text+0x4dea): undefined reference to `cv::Mat::deallocate()'
VideoFrameTransform.cpp:(.text+0x4e06): undefined reference to `cv::noArray()'
VideoFrameTransform.cpp:(.text+0x4e6a): undefined reference to `cv::Mat::setTo(cv::_InputArray const&, cv::_InputArray const&)'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `VideoFrameTransform::transformFramePlane(unsigned char*, unsigned char*, int, int, int, int, int, int, int, int)':
VideoFrameTransform.cpp:(.text+0x5208): undefined reference to `cv::fastFree(void*)'
VideoFrameTransform.cpp:(.text+0x5283): undefined reference to `cv::fastFree(void*)'
VideoFrameTransform.cpp:(.text+0x5311): undefined reference to `cv::String::allocate(unsigned long)'
VideoFrameTransform.cpp:(.text+0x5367): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
VideoFrameTransform.cpp:(.text+0x536f): undefined reference to `cv::String::deallocate()'
VideoFrameTransform.cpp:(.text+0x539e): undefined reference to `cv::Mat::deallocate()'
VideoFrameTransform.cpp:(.text+0x53b4): undefined reference to `cv::Mat::deallocate()'
VideoFrameTransform.cpp:(.text+0x53ec): undefined reference to `cv::String::allocate(unsigned long)'
VideoFrameTransform.cpp:(.text+0x5444): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
VideoFrameTransform.cpp:(.text+0x544e): undefined reference to `cv::String::deallocate()'
VideoFrameTransform.cpp:(.text+0x54f1): undefined reference to `cv::String::deallocate()'
VideoFrameTransform.cpp:(.text+0x5509): undefined reference to `cv::String::deallocate()'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `cv::MatExpr::~MatExpr()':
VideoFrameTransform.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x96): undefined reference to `cv::fastFree(void*)'
VideoFrameTransform.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x115): undefined reference to `cv::Mat::deallocate()'
VideoFrameTransform.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x125): undefined reference to `cv::Mat::deallocate()'
VideoFrameTransform.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x101): undefined reference to `cv::fastFree(void*)'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `void std::vector<cv::Mat, std::allocator<cv::Mat> >::_M_emplace_back_aux<cv::Mat&>(cv::Mat&)':
VideoFrameTransform.cpp:(.text._ZNSt6vectorIN2cv3MatESaIS1_EE19_M_emplace_back_auxIIRS1_EEEvDpOT_[_ZNSt6vectorIN2cv3MatESaIS1_EE19_M_emplace_back_auxIIRS1_EEEvDpOT_]+0x1dd): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
VideoFrameTransform.cpp:(.text._ZNSt6vectorIN2cv3MatESaIS1_EE19_M_emplace_back_auxIIRS1_EEEvDpOT_[_ZNSt6vectorIN2cv3MatESaIS1_EE19_M_emplace_back_auxIIRS1_EEEvDpOT_]+0x280): undefined reference to `cv::fastFree(void*)'
VideoFrameTransform.cpp:(.text._ZNSt6vectorIN2cv3MatESaIS1_EE19_M_emplace_back_auxIIRS1_EEEvDpOT_[_ZNSt6vectorIN2cv3MatESaIS1_EE19_M_emplace_back_auxIIRS1_EEEvDpOT_]+0x2d4): undefined reference to `cv::Mat::deallocate()'
VideoFrameTransform.cpp:(.text._ZNSt6vectorIN2cv3MatESaIS1_EE19_M_emplace_back_auxIIRS1_EEEvDpOT_[_ZNSt6vectorIN2cv3MatESaIS1_EE19_M_emplace_back_auxIIRS1_EEEvDpOT_]+0x2fa): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `void std::vector<cv::Mat, std::allocator<cv::Mat> >::emplace_back<cv::Mat&>(cv::Mat&)':
VideoFrameTransform.cpp:(.text._ZNSt6vectorIN2cv3MatESaIS1_EE12emplace_backIIRS1_EEEvDpOT_[_ZNSt6vectorIN2cv3MatESaIS1_EE12emplace_backIIRS1_EEEvDpOT_]+0xb8): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `void std::vector<cv::Mat, std::allocator<cv::Mat> >::_M_emplace_back_aux<cv::Mat const&>(cv::Mat const&)':
VideoFrameTransform.cpp:(.text._ZNSt6vectorIN2cv3MatESaIS1_EE19_M_emplace_back_auxIIRKS1_EEEvDpOT_[_ZNSt6vectorIN2cv3MatESaIS1_EE19_M_emplace_back_auxIIRKS1_EEEvDpOT_]+0x1dd): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
VideoFrameTransform.cpp:(.text._ZNSt6vectorIN2cv3MatESaIS1_EE19_M_emplace_back_auxIIRKS1_EEEvDpOT_[_ZNSt6vectorIN2cv3MatESaIS1_EE19_M_emplace_back_auxIIRKS1_EEEvDpOT_]+0x270): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
/usr/local/lib/libTransform360.a(VideoFrameTransform.cpp.o): In function `std::map<int, std::vector<cv::Mat, std::allocator<cv::Mat> >, std::less<int>, std::allocator<std::pair<int const, std::vector<cv::Mat, std::allocator<cv::Mat> > > > >::operator[](int const&)':
VideoFrameTransform.cpp:(.text._ZNSt3mapIiSt6vectorIN2cv3MatESaIS2_EESt4lessIiESaISt4pairIKiS4_EEEixERS8_[_ZNSt3mapIiSt6vectorIN2cv3MatESaIS2_EESt4lessIiESaISt4pairIKiS4_EEEixERS8_]+0x180): undefined reference to `cv::fastFree(void*)'
VideoFrameTransform.cpp:(.text._ZNSt3mapIiSt6vectorIN2cv3MatESaIS2_EESt4lessIiESaISt4pairIKiS4_EEEixERS8_[_ZNSt3mapIiSt6vectorIN2cv3MatESaIS2_EESt4lessIiESaISt4pairIKiS4_EEEixERS8_]+0x1b4): undefined reference to `cv::Mat::deallocate()'
collect2: error: ld returned 1 exit status
make: *** [ffmpeg_g] Error 1

It

**Comment by hangil2478** [comment]
For those of you who may face the same issue I had, I leave the setting environment.

Using ubuntu14.04, opencv-3.1.0, ffmpeg-3.1.11, the compilation was done properly.

Hopefully, this helps someone.
