### ISSUE TITLE
Offset Cubemap pipeline documentation

### ISSUE THREAD

**Issue by pleribus** [facebook/transform360#41]
I'm currently trying to utilise the offcenter cubemap format in a custom stereo VR video player built in Unity (for GearVR)

As previously mentioned by another user in [Issue 33](https://github.com/facebook/transform360/issues/33,) I'm seeing severe distortion around edges of cube and bowing in the image when it's brought over to Unity.  It is also destroying the stereo effect in the forward and back directions.

I assume I'm missing a key step when unwarping the resulting offset cubemap in Unity, but there is little to none in terms of information or documentation with regards to this.  

I had (wrongly?) assumed I could just offset the Unity camera by the same percentage used during the encode.

I'm looking at the talk about Offset Cubemaps here [https://www.youtube.com/watch?v=uSHTsGNFmeM&t=1424s](https://www.youtube.com/watch?v=uSHTsGNFmeM&t=1424s), and it mentions the following:

texture( cubeSampler, normailze(dir) + offset)

instead of

texture (cubeSampler, dir)

Can anyone talk more to this process of getting the distortions corrected back out at the other end?

I've also looked briefly at the OVROverlay in latest Mobile SDK, which talks of Offcenter Cubemaps, but having even more trouble ingesting the stereo 2x3 (LR) layout.

**Comment by pleribus** [comment]
Ok, I'm close.

Using a modified skymap shader and normalize(i.texcoord) + float4(0,0,-0.5,0), I can get the following.

Need to just figure out how to rotate the left front and right faces in the shader, and I think I've solved it.

![cubemap1](https://user-images.githubusercontent.com/2848681/31574430-82793cbc-b11b-11e7-8821-d26d896c565e.jpg)

![cubemap3](https://user-images.githubusercontent.com/2848681/31574460-484dd664-b11c-11e7-9a47-eec5c4008d64.jpg)

![cubemap2](https://user-images.githubusercontent.com/2848681/31574431-84de6414-b11b-11e7-8edf-6e5ded2af773.jpg)

**Comment by evgenykuzyakov** [comment]
Good luck with this. I think you're on the right path. Rotation and mirroring of faces is just UV manipulation.

**Comment by pleribus** [comment]
Thankyou.  I'm almost there.

Closing issue.  

Do recommend putting some more information in your Readme or link an article on Offset Cubemaps as there is very little information out there with regards to consuming at the player end.
