### ISSUE TITLE
ERROR: opencv not found

### ISSUE THREAD

**Issue by oyhngithub** [facebook/transform360#43]
According to the instruction :"Building on Ubuntu".
Everytime I tried   ./configure --prefix=/usr/local/transform/ffmpeg --enable-gpl --enable-nonfree --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libvpx --enable-libx264 --enable-libxvid --enable-libopencv --extra-libs='-lTransform360 -lstdc++'
It shows :ERROR: opencv not found. But I have already installed opencv.

Distro: Ubuntu 16.04.2 LTS , 
ffmpeg source: v3.4

**Comment by evgenykuzyakov** [comment]
@oyhngithub Why did you close this issue? Have you been able to resolve it? If so, can you please post how, because other people are having similar issues.

**Comment by oyhngithub** [comment]
@evgenykuzyakov I resolved this problem by changing the version of  FFmpeg source of 3.4 to 3.2.9 .Hope it helps.

**Comment by h4ck3r89** [comment]
Could you share how you set this up? The "specific steps" you followed to build transform360 and the OS and 32bit/64bit version details?

Thanks..:)

**Comment by oyhngithub** [comment]
Distro: Ubuntu 16.04 LTS 64bit
I followed exactly the same steps at README,except for download the FFMpeg 3.2.9 .The instruction is quite specific at README,I don't think I can make it better.
