### ISSUE TITLE
there is a line distortion between two faces in android 5.1 and opencves 3.1

### ISSUE THREAD

**Issue by xuws20** [facebook/transform360#44]
but it is good in PC and windows10 and opengles 3.1.

**Comment by evgenykuzyakov** [comment]
Please add more details with screenshots. It's probably related to expansion coefficient for each cubemap face.

**Comment by xuws20** [comment]
it happens only in android5.1 and opengles 3.1. but in windows and opengles3.1 , there is no line distortion.

**Comment by xuws20** [comment]
Problem  has been already solved. Interpolation model is modified from GL_LINEAR to GL_NEAREST.Thanks.

**Comment by evgenykuzyakov** [comment]
It's probably not the interpolation that causes the seam to be visible. Something is off with UV coordinates. The correct padding for rendering is (1.0 - 1.0/expand_coef) * 0.5 from each side of each face. So if expand_coef is 1.01, the padding should be 0.5 / 101.0

**Comment by h4ck3r89** [comment]
Could you share how you set this up? The steps you followed to build transform360 and the OS and 32bit/64bit version details?

Thanks..:)

**Comment by xuws20** [comment]
you are right。After  the interpolation mode is changed, image quality is getting worse。
expand=coef=1.003，off_x = (1.0 - 1.0/expand_coef) * 0.5 /3.0f,off_y=(1.0 - 1.0/expand_coef) * 0.5 /2.0f

**Comment by evgenykuzyakov** [comment]
expand_coef=1.003 is probably too small for 896. Since you're likely using yuv420, you need at least 2 pixels from each side of the face to avoid color seams. And this assumption ignores compression artifacts, which are not as obvious.
So you need 1 + 4 / 896=0.00446428571. Try using expand_coef=1.005

**Comment by evgenykuzyakov** [comment]
Ok, closing for now. Reopen if you need more help.
