### ISSUE TITLE
transform360 doesn't offer "FLAT_FIXED" output_layout

### ISSUE THREAD

**Issue by agrathwohl** [facebook/transform360#48]
transform360 appears to not offer the output_layout `FLAT_FIXED`, which was offered in transform_v1. Running `./ffmpeg -h filter=transform360` produces the following output_layout options:

```
  output_layout     <int>        ..FV.... Output video layout format (from 0 to 4) (default CUBEMAP_32)
     CUBEMAP_32                   ..FV....
     CUBEMAP_23_OFFCENTER              ..FV....
     EQUIRECT                     ..FV....
     BARREL                       ..FV....
     EAC_32                       ..FV....
     cubemap_32                   ..FV....
     cubemap_23_offcenter              ..FV....
     equirect                     ..FV....
     barrel                       ..FV....
     eac_32                       ..FV....
```

transform360 offers great quality and performance improvements, but in order to adopt it, I will need to be able to output flat versions of my equirectangular content, like I could with transform_v1. Are there any plans to re-implement `FLAT_FIXED` layout into transform360? If not, are there other means by which I can use transform360 to achieve the same outcome as transform_v1's `FLAT_FIXED`?

**Comment by kcircnc** [comment]
Thanks for the feedback. I've added it to Transform360. Enjoy.

**Comment by agrathwohl** [comment]
Thanks very much for adding it to Transform360. I will close out this issue now. Cheers!
