### ISSUE TITLE
Recommended filter settings for 4K sources 

### ISSUE THREAD

**Issue by danrossi** [facebook/transform360#50]
Hi there. I am just wondering on extra information about recommended filter settings for 4K sources ? 

With this config

```
cube_edge_length=512 
```

Each cube is a pow2 512 dimension. Making the video dimension 1024 pixels in height. Is this still good quality or should it be matching the source dimension ? 

Is a lower cube dimension the whole point of same quality for reduced bandwidth ? 

Without a bitrate encoder setting the bitrate is reduced from the source also. 

After the new include path change I am able to run an ffmpeg encode finally to check its output. It encodes to cubemap correctly.

**Comment by ethanjyx** [comment]
For 4K, the recommended setting is to make the cube_edge_length=1024. The cube length would be 1/4 * original_width, for 4K videos the original width is 4096, so we set cube edge length as 1024. As for why we use 1/4, you can read more in https://en.wikipedia.org/wiki/Cube_mapping, the original width should be the sum of the back, left, front, right faces. 

The lower cube dimension will reduce the number of pixels thus bandwidth and achieve similar qualities as original. 

Let us know if you have more questions.

**Comment by danrossi** [comment]
That is great thanks for that. Closing. The compilation all works and encode works also.
