### ISSUE TITLE
Question about multi-threading and segments

### ISSUE THREAD

**Issue by EthanXzhang** [facebook/transform360#51]
I generally read the source code of Transform360. I get some question about the segments and multi-threading low-pass filter.
As I read the method of generateKernelAndFilteringConfig, segment is used to divide the frame into every small segment and init the config of every menber of vector. And then, when process the Frame plane, the method of opencv sepFilter2D will process every small segment.
If the segment decide the number of threads, the filter may speed up with the number of threads increasing.But, the result is totally opposite.
Is the number of segment increasing means the quality of the low-pass filter increasing?
Maybe I get a wrong understand, hope someone can help me，thanks！

**Comment by EthanXzhang** [comment]
I have calculated the PSNR of the enable/disable Mutli-threading, the output frame with the Ref of the source Frame(ERP to CUBE to ERP) have the same PSNR. It means that Mutli-Threading is non-increasing in the quality of the low-pass filter.
But, why it slow down the speed?

**Comment by ethanjyx** [comment]
Hi @EthanXzhang , what were the commands that you used for enabling and disabling multi-threading?

**Comment by EthanXzhang** [comment]
@ethanjyx Refer to the README, commands like"... :enable_low_pass_filter=1 :enable_multi_threading=1 :num_horizontal_segments=2 :num_vertical_segments=1..."
I have figure out this question. The number of threads has a threshold. 2K Frame have a low threshold. When the number of segment reached the threshold(under 10), the speed begins to become less obvious or reduce. In 4K Frame, MT Low-pass Filter have a good performance.
Sorry to report it late.
Thanks a lot.
