### ISSUE TITLE
FYI: branch with Transform360 patch pre-applied.

### ISSUE THREAD

**Issue by sjuxax** [facebook/transform360#57]
Not a big deal, but leaving here for posterity in case it helps anyone out: https://github.com/sjuxax/FFmpeg/tree/transform360 . This branch has the patches necessary to build the Transform360 filter pre-applied. Leaving here since I was pushing a different branch up anyway, as described in #56 .

**Comment by samuelgirardin** [comment]
Hi sjuxax, what do you mean by Transform360 filter pre-applied ? does this solve the libopencv not found ?

**Comment by sjuxax** [comment]
No, this just follows the process documented in the README to make the Transform360 filter available to ffmpeg. It's there in case it's easier for someone to pull the patch than to follow the steps outlined in the README. This issue does not really need attention, it was just a way to drop off the branch in case it helps someone, since I was here on the issues page anyway to discuss OpenCV. Will close.

At the moment, you'll need to install OpenCV 3.4.0 or earlier to fix the build issues. I do have a branch that began the process of fixing that at https://github.com/sjuxax/FFmpeg/tree/cpp_opencv , but it doesn't build yet and I don't really plan on plumbing it through. I assume someone in the ffmpeg project will fix this upstream relatively soon.
