### ISSUE TITLE
Segment fault (core dumped)

### ISSUE THREAD

**Issue by ltl6238788** [facebook/transform360#68]
When I finish the installation, I follow the instructions to try projection conversion. The command I enter is in the document:

ffmpeg -i input.mp4

-vf transform360="input_stereo_format=MONO

:cube_edge_length=512

: interpolation? Alg = cubic

:enable_low_pass_filter=1

:enable_multi_threading=1

:num_horizontal_segments=32

:num_vertical_segments=15

: adjust_kernel = 1“

Output.mp4

However, the following error occurred:

ffmpeg version 4.1.4 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 5.5.0 (Ubuntu 5.5.0-12ubuntu1~16.04) 20171010

configuration: --prefix=/usr/local/transform/ffmpeg --enable-gpl --enable-nonfree --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libvpx --enable-libx264 --enable-libxvid --enable-libopencv --extra-libs='-lTransform360 -lstdc++'

libavutil 56. 22.100 / 56. 22.100

libavcodec 58. 35.100 / 58. 35.100

libavformat 58. 20.100 / 58. 20.100

libavdevice 58. 5.100 / 58. 5.100

libavfilter 7. 40.101 / 7. 40.101

libswscale 5. 3.100 / 5. 3.100

libswresample 3. 3.100 / 3. 3.100

libpostproc 55. 3.100 / 55. 3.100

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'input.mp4':

Metadata:

major_brand : mp42

minor_version : 19529854

compatible_brands: mp42isom

creation_time : 2015-06-05T02:22:01.000000Z

Duration: 00:01:41.48, start: 0.000000, bitrate: 13888 kb/s

Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s (default)

Metadata:

creation_time : 2015-06-05T02:22:01.000000Z

handler_name : Sound Media Handler

Stream #0:1(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv), 1920x1080 [SAR 1:1 DAR 16:9], 13692 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)

Metadata:

creation_time : 2015-06-05T02:22:01.000000Z

handler_name : Video Media Handler

encoder : AVC Coding

File '=input_stereo_format = MONO: cube_edge_length = 512: interpolation_alg = cubic: enable_low_pass_filter = 1: enable_multi_threading = 1: num_horizontal_segments=32: num_vertical_segments = 15: djust_kernel = 1output.mp4' already exists. Overwrite ? [y/N] y

Stream mapping:

Stream #0:1 -> #0:0 (h264 (native) -> h264 (libx264))

Stream #0:0 -> #0:1 (aac (native) -> aac (native))

Press [q] to stop, [?] for help

Segment fault (core dumped)

I tried different versions of ffmpeg and GCC, but they can't solve this problem. Who knows how to solve this problem?

**Comment by kcircnc** [comment]
> File '=input_stereo_format = MONO: cube_edge_length = 512: interpolation_alg = cubic: enable_low_pass_filter = 1: enable_multi_threading = 1: num_horizontal_segments=32: num_vertical_segments = 15: djust_kernel = 1output.mp4' already exists. Overwrite ? [y/N] y

This shows that ffmpeg thinks your params for transform360 is an output file name. This is not a transform360 issue since you haven't reached the filter yet. Here is the synopsis of ffmpeg commands: https://www.ffmpeg.org/ffmpeg.html#Synopsis
