### ISSUE TITLE
pyramidal projection support

### ISSUE THREAD

**Issue by abuisine** [facebook/transform360#7]
is there any plan to release pyramidal projection as well ?

**Comment by palfu** [comment]
+1

**Comment by miraclestar** [comment]
+1

**Comment by gwendalsimon** [comment]
Hi,
We have developed a tool to project into cubemap, equirectangular, pyramidal and rhombic dodecahedron:
https://github.com/xmar/360Transformations

In addition, we have added a special feature where the encoding quality of the projection can vary within the frame. It is the starting point for "viewport-adaptive 360-degree delivery system"
https://github.com/xmar/360Transformations/blob/master/academicPaper/blog/post.rst

Comments and contributions welcomed!

**Comment by puffpio** [comment]
we actually deprecated using pyramid internally in favor of using offset cubemaps (which are included in the latest version). we don't plan on releasing pyramid projection as offset cubemap is superior.

thanks
